//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAndCours
    {
        public int Id { get; set; }
        public string IdCustomer { get; set; }
        public int IdCourse { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual NormalSport NormalSport { get; set; }
    }
}
