//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TherapeuticSport
    {
        public TherapeuticSport()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int IdCourseT { get; set; }
        public bool ThereIsReference { get; set; }
        public string TypeOfDisability { get; set; }
        public string AreaOfDisability { get; set; }
        public Nullable<int> HowPrescription { get; set; }
        public string ThereIsImprove { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
