//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeFull
    {
        public TimeFull()
        {
            this.Courses = new HashSet<Cours>();
        }
    
        public int Id { get; set; }
        public int Hour { get; set; }
        public int Minute { get; set; }
    
        public virtual ICollection<Cours> Courses { get; set; }
    }
}
